//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Resources.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModel.Resources.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  activated successfully..
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add one service billing.
        /// </summary>
        public static string Add_one_bill {
            get {
                return ResourceManager.GetString("Add-one-bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please add at least one date.&quot;.
        /// </summary>
        public static string AddOneDate {
            get {
                return ResourceManager.GetString("AddOneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact administrator!.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be greater than zero..
        /// </summary>
        public static string Age_0 {
            get {
                return ResourceManager.GetString("Age>0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already cancelled.
        /// </summary>
        public static string Al_Can {
            get {
                return ResourceManager.GetString("Al-Can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocular alignment is required..
        /// </summary>
        public static string Alignment_ {
            get {
                return ResourceManager.GetString("Alignment?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   already exist..
        /// </summary>
        public static string Already {
            get {
                return ResourceManager.GetString("Already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount cannot be less than or equal to zero.
        /// </summary>
        public static string Amount___0 {
            get {
                return ResourceManager.GetString("Amount !>0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing service amount removed successfully!.
        /// </summary>
        public static string BillAmountRemove {
            get {
                return ResourceManager.GetString("BillAmountRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CampId is missing.
        /// </summary>
        public static string CampId {
            get {
                return ResourceManager.GetString("CampId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel approved successfully!&quot;.
        /// </summary>
        public static string Can_Appr_Success {
            get {
                return ResourceManager.GetString("Can-Appr-Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First cancel service billing.
        /// </summary>
        public static string Can_Ser_Billing {
            get {
                return ResourceManager.GetString("Can-Ser-Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Cancel successfully!.
        /// </summary>
        public static string Cancel_successfully {
            get {
                return ResourceManager.GetString("Cancel successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As screening has been started ,you can not edit camp.
        /// </summary>
        public static string CanNotEdit {
            get {
                return ResourceManager.GetString("CanNotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint is required..
        /// </summary>
        public static string Complaint_ {
            get {
                return ResourceManager.GetString("Complaint?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to {0}?.
        /// </summary>
        public static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number must be at least 10 digits..
        /// </summary>
        public static string ContactNo__10 {
            get {
                return ResourceManager.GetString("ContactNo.>10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Data deleted successfully!.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is required.
        /// </summary>
        public static string Desig_ {
            get {
                return ResourceManager.GetString("Desig?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cannot exceed the total amount..
        /// </summary>
        public static string Dis___TotalAmt {
            get {
                return ResourceManager.GetString("Dis !>TotalAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cannot exceed the service cost.
        /// </summary>
        public static string Dis__ServiceAmt {
            get {
                return ResourceManager.GetString("Dis!>ServiceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount is already approved.
        /// </summary>
        public static string Dis_al_app {
            get {
                return ResourceManager.GetString("Dis-al-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount approved successfully!.
        /// </summary>
        public static string DisApproved {
            get {
                return ResourceManager.GetString("DisApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive record cannot be edited!.
        /// </summary>
        public static string Edited {
            get {
                return ResourceManager.GetString("Edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter amount.
        /// </summary>
        public static string Ent_Amt {
            get {
                return ResourceManager.GetString("Ent-Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading dates.
        /// </summary>
        public static string ErrorloadDate {
            get {
                return ResourceManager.GetString("ErrorloadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye selection is required.
        /// </summary>
        public static string Eye_ {
            get {
                return ResourceManager.GetString("Eye?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch .
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch activity dates. Please try again..
        /// </summary>
        public static string FailedActivatyDate {
            get {
                return ResourceManager.GetString("FailedActivatyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the EMR/IP No..
        /// </summary>
        public static string FillEMR {
            get {
                return ResourceManager.GetString("FillEMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill at least one field before search..
        /// </summary>
        public static string FillOneField {
            get {
                return ResourceManager.GetString("FillOneField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient&apos;s first name..
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter identity number.
        /// </summary>
        public static string IdentiyNo_ {
            get {
                return ResourceManager.GetString("IdentiyNo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  inactivated successfully..
        /// </summary>
        public static string Inactivated {
            get {
                return ResourceManager.GetString("Inactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  inserted successfully!.
        /// </summary>
        public static string Inserted {
            get {
                return ResourceManager.GetString("Inserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the correct {0}..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmark/House No. is required..
        /// </summary>
        public static string Landmark_ {
            get {
                return ResourceManager.GetString("Landmark?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total lens amount cannot be negative.
        /// </summary>
        public static string lenAmt____0 {
            get {
                return ResourceManager.GetString("lenAmt !> 0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch address details..
        /// </summary>
        public static string NoAddressdetails {
            get {
                return ResourceManager.GetString("NoAddressdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch area list.
        /// </summary>
        public static string NoAreaList {
            get {
                return ResourceManager.GetString("NoAreaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  remarks cannot be blank.
        /// </summary>
        public static string NoBlankRemark {
            get {
                return ResourceManager.GetString("NoBlankRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount is not provided.
        /// </summary>
        public static string NoDiscount {
            get {
                return ResourceManager.GetString("NoDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch group list.
        /// </summary>
        public static string NoGroupList {
            get {
                return ResourceManager.GetString("NoGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment head amount cannot be zero (0.00). Please ensure the head amount is properly mapped to the appropriate (Regional Hospital / Vision Center)..
        /// </summary>
        public static string NoHeadAmountSet {
            get {
                return ResourceManager.GetString("NoHeadAmountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch hospital list.
        /// </summary>
        public static string NoHospitalList {
            get {
                return ResourceManager.GetString("NoHospitalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list not found.
        /// </summary>
        public static string NoList {
            get {
                return ResourceManager.GetString("NoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found for the current date.
        /// </summary>
        public static string NoRecordDate {
            get {
                return ResourceManager.GetString("NoRecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found for the selected date.
        /// </summary>
        public static string NoRecordOnDate {
            get {
                return ResourceManager.GetString("NoRecordOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data received from the server.
        /// </summary>
        public static string NoServerData {
            get {
                return ResourceManager.GetString("NoServerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not integrated with EMR / HMS. .
        /// </summary>
        public static string Not_Int_EMR {
            get {
                return ResourceManager.GetString("Not_Int_EMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Blank.
        /// </summary>
        public static string NotBlank {
            get {
                return ResourceManager.GetString("NotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not enroll same patient on same date!.
        /// </summary>
        public static string NotEnrollOnSameDate {
            get {
                return ResourceManager.GetString("NotEnrollOnSameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not matched with confirm password!.
        /// </summary>
        public static string PassNotMatch {
            get {
                return ResourceManager.GetString("PassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long with upper &amp; lower case letters, a digit, and a special character..
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient checkout successfully.
        /// </summary>
        public static string PatientCheckout {
            get {
                return ResourceManager.GetString("PatientCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient enrolled successfully!.
        /// </summary>
        public static string PatientEnroll {
            get {
                return ResourceManager.GetString("PatientEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment successfully.
        /// </summary>
        public static string Pay_Success {
            get {
                return ResourceManager.GetString("Pay-Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select payment mode..
        /// </summary>
        public static string Payment_Mode {
            get {
                return ResourceManager.GetString("Payment Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period is required and must be greater than 0..
        /// </summary>
        public static string Period_ {
            get {
                return ResourceManager.GetString("Period?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Type is required.
        /// </summary>
        public static string PeriodType_ {
            get {
                return ResourceManager.GetString("PeriodType?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to take photo to save it..
        /// </summary>
        public static string Photo_Save {
            get {
                return ResourceManager.GetString("Photo_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already active..
        /// </summary>
        public static string RecordAct {
            get {
                return ResourceManager.GetString("RecordAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already inactive..
        /// </summary>
        public static string RecordUnactive {
            get {
                return ResourceManager.GetString("RecordUnactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select referral for!.
        /// </summary>
        public static string Referralfor {
            get {
                return ResourceManager.GetString("Referralfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Registration complete successfully!.
        /// </summary>
        public static string RegSave {
            get {
                return ResourceManager.GetString("RegSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks are required..
        /// </summary>
        public static string Remarks_ {
            get {
                return ResourceManager.GetString("Remarks?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removed successfully.
        /// </summary>
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove hospital referral details?.
        /// </summary>
        public static string RemoveReferralDetails {
            get {
                return ResourceManager.GetString("RemoveReferralDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove spectacles management details?.
        /// </summary>
        public static string RemoveSpectMangDetails {
            get {
                return ResourceManager.GetString("RemoveSpectMangDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        public static string Required_1 {
            get {
                return ResourceManager.GetString("Required?1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        public static string Required_2 {
            get {
                return ResourceManager.GetString("Required?2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        public static string Required_3 {
            get {
                return ResourceManager.GetString("Required?3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be blank .
        /// </summary>
        public static string RequiredField1 {
            get {
                return ResourceManager.GetString("RequiredField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved successfully!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select donor.
        /// </summary>
        public static string Sel_Donor {
            get {
                return ResourceManager.GetString("Sel-Donor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select gender..
        /// </summary>
        public static string Sel_Gender {
            get {
                return ResourceManager.GetString("Sel_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vision van.
        /// </summary>
        public static string Sel_Van {
            get {
                return ResourceManager.GetString("Sel-Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select hospital.
        /// </summary>
        public static string Select_Hosp {
            get {
                return ResourceManager.GetString("Select-Hosp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user type.
        /// </summary>
        public static string Select_User {
            get {
                return ResourceManager.GetString("Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select vision center.
        /// </summary>
        public static string Select_VC {
            get {
                return ResourceManager.GetString("Select-VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue with selected patient?.
        /// </summary>
        public static string SelectedPatient {
            get {
                return ResourceManager.GetString("SelectedPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Ocular examination (RE) or (LE) field!.
        /// </summary>
        public static string SelectOneOcularExamFiled {
            get {
                return ResourceManager.GetString("SelectOneOcularExamFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Refraction (RE) or (LE) Previous Glasses Prescription field!.
        /// </summary>
        public static string SelectOneRefraction {
            get {
                return ResourceManager.GetString("SelectOneRefraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Surgery.
        /// </summary>
        public static string SelectSurgery {
            get {
                return ResourceManager.GetString("SelectSurgery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected service cost is 0.00..
        /// </summary>
        public static string ServiceCost_0_00 {
            get {
                return ResourceManager.GetString("ServiceCost_0.00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacles hand over details saved successfully!.
        /// </summary>
        public static string Spec_handOver_Save {
            get {
                return ResourceManager.GetString("Spec-handOver-Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacles hand over details updated successfully!.
        /// </summary>
        public static string Spec_handOver_update {
            get {
                return ResourceManager.GetString("Spec-handOver-update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectacle has not been hand over so you can not print optical invoice reciept..
        /// </summary>
        public static string Spect_Not_Handover {
            get {
                return ResourceManager.GetString("Spect-Not-Handover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select spectacle status.
        /// </summary>
        public static string SpectacleStatus {
            get {
                return ResourceManager.GetString("SpectacleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot exceed {1} characters.
        /// </summary>
        public static string StringLengthExceeded {
            get {
                return ResourceManager.GetString("StringLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  submit successfully!.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date cannot be less than from date.
        /// </summary>
        public static string ToDate__FromDate {
            get {
                return ResourceManager.GetString("ToDate!>FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total lens amount cannot be negative.
        /// </summary>
        public static string TotalLensAmt_0 {
            get {
                return ResourceManager.GetString("TotalLensAmt>0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  updated successfully!.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Amount.
        /// </summary>
        public static string Valid_Amt {
            get {
                return ResourceManager.GetString("Valid_Amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid age..
        /// </summary>
        public static string ValidAge {
            get {
                return ResourceManager.GetString("ValidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit date cannot be less than the current date..
        /// </summary>
        public static string VisitDate_CurrentDate {
            get {
                return ResourceManager.GetString("VisitDate>CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select visit to hospital.
        /// </summary>
        public static string VisitToHospital {
            get {
                return ResourceManager.GetString("VisitToHospital", resourceCulture);
            }
        }
    }
}
