//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class BankAccount
    {
        private BankAccountModel accountModel = new();
        private string olddesignation = "";
        private List<BankModel> Banklist = new();
        private List<BankAccountModel> bankAccountlist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "Finance/GetBank";
            Banklist = await httpService.Get<List<BankModel>>(ApiUri) ?? new();
            string ApiUri1 = "BankAccount/GetBankAccount";
            bankAccountlist = await httpService.Get<List<BankAccountModel>>(ApiUri1) ?? new();
            IsLoading = false;
        }


        private void AddAccount()
        {
            accountModel = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            ShowPopup = false;
            accountModel = new();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {
                if (accountModel.DetBankAcId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(accountModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                accountModel.IsValid = true;
                accountModel.GroupCode = groupcode;
                accountModel.BranchCode = branchcode;
                accountModel.CreatedBy = UserName;
                accountModel.CreatedDate = DateTime.Now;
                accountModel.LastTransDate = DateTime.Now;
                string apiUrl = "BankAccount/AddOrUpdateBankAccount";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, accountModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Account" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Account" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Account" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                accountModel = new BankAccountModel();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               
                StateHasChanged();
            }
        }

        private void EditAccount(BankAccountModel item)
        {
            accountModel = new BankAccountModel
            {
                DetBankAcId = item.DetBankAcId,
                AccountNo = item.AccountNo,
                AccountType = item.AccountType,
                DisplayName = item.DisplayName,
                BankId = item.BankId
            };
            olddesignation = CommonMethod.CreateSnapshot(accountModel);
            ShowPopup = true;
        }

        protected IQueryable<BankAccountModel> FilteredItems
        {
            get
            {
                var result = bankAccountlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.AccountType != null && x.AccountType.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeAccountStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "BankAccount/DeleteBankAccount";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}