//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class ChequeBook
    {
        private ChequeBookModel chequeBookModel = new();
        private string olddesignation = "";
        private List<BankModel> Banklist = new();
        private List<ChequeBookModel> chequelist = new();
        private List<AccountNoModel> accountlist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri2 = "AccountNo/GetAccountNo";
            accountlist = await httpService.Get<List<AccountNoModel>>(ApiUri2) ?? new();
            string ApiUri = "Finance/GetBank";
            Banklist = await httpService.Get<List<BankModel>>(ApiUri) ?? new();
            string ApiUri1 = "ChequeBook/GetCheckBook";
            chequelist = await httpService.Get<List<ChequeBookModel>>(ApiUri1) ?? new();
            IsLoading = false;
        }


        private void AddChequeModel()
        {
            chequeBookModel = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            ShowPopup = false;
            chequeBookModel = new();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {
                if (chequeBookModel.CheqBookId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(chequeBookModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                chequeBookModel.IsValid = true;
                chequeBookModel.GroupCode = groupcode;
                chequeBookModel.BranchCode = branchcode;
                chequeBookModel.CreatedBy = UserName;
                //ChequeModel.CreatedDate = DateTime.Now;
                string apiUrl = "ChequeBook/AddOrUpdateCheckBook";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, chequeBookModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Cheque Name " + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Cheque Name " + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Cheque Name " + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                chequeBookModel = new ChequeBookModel();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
            }
        }

        private void EditCheque(ChequeBookModel item)
        {
            chequeBookModel = new ChequeBookModel
            {
                CheqBookId = item.CheqBookId,
                CheqTitle = item.CheqTitle,
                BankId = item.BankId,
                AccountId = item.AccountId
            };
            olddesignation = CommonMethod.CreateSnapshot(chequeBookModel);
            ShowPopup = true;
        }

        protected IQueryable<ChequeBookModel> FilteredItems
        {
            get
            {
                var result = chequelist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.CheqTitle != null && x.CheqTitle.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeChequeStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "ChequeBook/DeleteFINCheque";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}