//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class ChequeType
    {
        private ChequeTypeModel ChequeTypeModel = new();
        private string olddesignation = "";
        private List<ChequeTypeModel> ChequeTypelist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        private void AddChequeTypeModel()
        {
            ChequeTypeModel = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            ShowPopup = false;
            ChequeTypeModel = new();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {
                if (ChequeTypeModel.Sid > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(ChequeTypeModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                ChequeTypeModel.IsValid = true;
                ChequeTypeModel.GroupCode = groupcode;
                ChequeTypeModel.BranchCode = branchcode;
                ChequeTypeModel.CreatedBy = UserName;
                //ChequeTypeModel.CreatedDate = DateTime.Now;
                string apiUrl = "ChequeType/AddOrUpdateChecktype";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, ChequeTypeModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Cheque Type  " + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Cheque Type  " + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Cheque Type  " + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                ChequeTypeModel = new ChequeTypeModel();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
            }
        }

        private void EditChequeType(ChequeTypeModel item)
        {
            ChequeTypeModel = new ChequeTypeModel
            {
                Sid = item.Sid,
                ChequeTypeName = item.ChequeTypeName,
                DisplayOrder = item.DisplayOrder
            };
            olddesignation = CommonMethod.CreateSnapshot(ChequeTypeModel);
            ShowPopup = true;
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "ChequeType/GetChecktype";
            ChequeTypelist = await httpService.Get<List<ChequeTypeModel>>(ApiUri) ?? new();
            IsLoading = false;
        }

        protected IQueryable<ChequeTypeModel> FilteredItems
        {
            get
            {
                var result = ChequeTypelist.OrderBy(x => x.DisplayOrder).AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ChequeTypeName != null && x.ChequeTypeName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                   (x.DisplayOrder != 0 && x.DisplayOrder.ToString().Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeChequeTypeStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "ChequeType/DeleteChecktype";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}