////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//using DocumentFormat.OpenXml.Bibliography;
//using DomainModel.Admin;
//using DomainModel.FinanceMNGT;
//using Microsoft.AspNetCore.Components.QuickGrid;
//using Microsoft.JSInterop;
//using MyApp.Common;

//namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
//{
//    public partial class FeeCollection
//    {
//        private FeeCollectionModel feeCollection = new();
//        private string olddesignation = ""; 
//        private List<FeeCollectionModel> feeCollectionlist = new();
//        private List<BranchClassModel> classlist = new();
//        private List<SessionModel> sessionlist = new();
//        private List<MonthModel> monthlist = new();
//        private List<FeeHeadModel> feeHeadlist = new();
//        private string nameFilter = string.Empty;
//        PaginationState pagination = new() { ItemsPerPage = 15 };
//        private string statusFilter = "1";
//        private bool IsLoading = true;
//        private bool ShowPopup;
//        private string branchcode;
//        private string groupcode;
//        private string UserName;
//        private string? currentUrl;
//        protected override void OnInitialized()
//        {

//            PermissionState.OnChange += StateHasChanged;
//            currentUrl = Nav.Uri;
//            StateHasChanged();

//        }
//        private void AddFeeCollection()
//        {
//            feeCollection = new();
//            ShowPopup = true;
//        }
//        private void ClosePopup()
//        {
//            ShowPopup = false;
//            feeCollection = new();
//            StateHasChanged();
//        }
//        protected override async Task OnAfterRenderAsync(bool firstRender)
//        {
//            if (firstRender)
//            {
//                await LoadData();
//                StateHasChanged();
//            }
//        }

//        private async Task LoadData()
//        {
//            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
//            branchcode = branchResult.Value;
//            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
//            groupcode = groupResult.Value;
//            var username = await sessionStorage.GetAsync<string>("UserName");
//            UserName = username.Value;
//            IsLoading = true;
//            string ApiUri = "FeeCollection/GetFeeCollection";
//            feeCollectionlist = await httpService.Get<List<FeeCollectionModel>>(ApiUri) ?? new();
//            string ApiUri1 = "Month/GetMonth";
//            classlist = await httpService.Get<List<BranchClassModel>>("BranchClass/GetClassCode") ?? new();
//            monthlist = await httpService.Get<List<MonthModel>>(ApiUri1) ?? new();
//            string ApiUri2 = "Session/GetSession";
//            sessionlist = await httpService.Get<List<SessionModel>>(ApiUri2) ?? new();
//            string ApiUri3 = "FeeHead/GetFeeHeadList";
//            feeHeadlist = await httpService.Get<List<FeeHeadModel>>(ApiUri3) ?? new();
//            IsLoading = false;
//        }
//        private async Task OnSave()
//        {

//            try
//            {
//                if (feeCollection.Sid > 0)
//                {
//                    ShowPopup = false;
//                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
//                    if (!isConfirmed)
//                    {
//                        ShowPopup = true;
//                        return;
//                    }
//                    bool isSame = CommonMethod.IsEdited(feeCollection, olddesignation);
//                    if (!isSame)
//                    {
//                        await Alert.ShowWarning("No changes detected.");
//                        ShowPopup = true;
//                        return;
//                    }
//                }
             
//                ShowPopup = false;
//                if (feeCollection.SessionId==0)
//                {
//                    await Alert.ShowWarning("Please select a session");
//                    ShowPopup = true;
//                    return;
//                }
//                feeCollection.IsValid = true;
//                feeCollection.GroupCode = groupcode;
//                feeCollection.BranchCode = branchcode;
//                feeCollection.CreatedBy = UserName;
//                string apiUrl = "FeeCollection/AddOrUpdateFeeCollection";
//                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, feeCollection);
//                var responsecode = apiResponse.Code;
//                if (responsecode == 0)
//                {
//                    await Alert.ShowWarning("Fee Collection" + @Localizer["Already"]);
//                }
//                else if (responsecode == 1)
//                {
//                    await Alert.ShowSuccess("Fee Collection" + @Localizer["Inserted"]);
//                }
//                else if (responsecode == 2)
//                {
//                    await Alert.ShowUpdate("Fee Collection" + @Localizer["Updated"]);
//                }
//                else
//                {
//                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
//                }
//                await LoadData();
//                feeCollection = new FeeCollectionModel();
//            }
//            catch (Exception ex)
//            {
//                return;
//            }
//            finally
//            {
               
//                StateHasChanged();
//            }
//        }

//        private void EditFeeCollection(FeeCollectionModel item)
//        {
//            feeCollection = new FeeCollectionModel
//            {
//                Sid = item.Sid,
//                SessionId=item.SessionId,
//                FeeHeadId = item.FeeHeadId,
//                ClassCode = item.ClassCode,
//                SessionName = item.SessionName,
//                MonthNo = item.MonthNo,
//                Amount = item.Amount
//            };
//            olddesignation = CommonMethod.CreateSnapshot(feeCollection);
//            ShowPopup = true;
//        }


//        protected IQueryable<FeeCollectionModel> FilteredItems
//        {
//            get
//            {
//                var result = feeCollectionlist.AsQueryable();
//                if (!string.IsNullOrEmpty(nameFilter))
//                {
//                    result = result.Where(x => x.Amount != 0 && x.Amount.ToString().Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase));

//                }
//                if (statusFilter == "1")
//                {
//                    result = result.Where(s => s.IsValid);
//                }
//                else if (statusFilter == "0")
//                {
//                    result = result.Where(s => !s.IsValid);
//                }
//                return result;
//            }
//        }
//        private string GetStatusClass(bool isActive)
//        {
//            return isActive ? "activeClr" : "inactiveClr";

//        }
//        private void FilterChangedAsync(int filterValue)
//        {
//            statusFilter = filterValue.ToString();
//            StateHasChanged();
//        }
//        private async Task ChangeFeeCollectionStatus(int id, bool isValid)
//        {
//            try
//            {
//                bool isActivate = !isValid;
//                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
//                if (!isConfirmed)
//                    return;

//                string apiUrl = "FeeCollection/DeleteFeeCollection";

//                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

//                if (apiResponse.Success)
//                {
//                    if (isActivate)
//                        await Alert.ShowActive(Localizer["Activated"]);
//                    else
//                        await Alert.ShowDeactive(Localizer["Deleted"]);

//                    await LoadData();
//                    StateHasChanged();
//                }
//                else
//                {
//                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
//                }
//            }
//            catch (Exception ex)
//            {
//                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
//            }
//            finally
//            {
//                StateHasChanged();
//                await LoadData();
//            }
//        }
//    }
//}