//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class FeeHead
    {
        private FeeHeadModel feeHeadModel = new();
        private string olddesignation = "";
        private List<FeeHeadModel> feeHeadlist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        private void AddFeeHeadModel()
        {
            feeHeadModel = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            feeHeadModel = new();
            ShowPopup = false;
            StateHasChanged();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                StateHasChanged();

            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            var username = await sessionStorage.GetAsync<string>("UserName");
            UserName = username.Value;
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "FeeHead/GetFeeHeadList";
            feeHeadlist = await httpService.Get<List<FeeHeadModel>>(ApiUri) ?? new();
            IsLoading = false;
        }
        private async Task OnSave()
        {

            try
            {
                if (feeHeadModel.FeeHeadId > 0)
                {


                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(feeHeadModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                feeHeadModel.IsValid = true;
                feeHeadModel.GroupCode = groupcode;
                feeHeadModel.BranchCode = branchcode;
                feeHeadModel.CreatedBy = UserName;
                string apiUrl = "FeeHead/AddUpdateFeeHead";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, feeHeadModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Fee Head" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Fee Head" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Fee Head" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                feeHeadModel = new FeeHeadModel();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
            }
        }

        private void EditFeeHead(FeeHeadModel item)
        {
            feeHeadModel = new FeeHeadModel
            {
                FeeHeadId = item.FeeHeadId,
                FeeHeadName = item.FeeHeadName,
                FeeApplicableType = item.FeeApplicableType,
                FeeHeadAbbr = item.FeeHeadAbbr,
                DisplayOrder = item.DisplayOrder,
                FeeHeadType = item.FeeHeadType
            };
            olddesignation = CommonMethod.CreateSnapshot(feeHeadModel);
            ShowPopup = true;
        }


        protected IQueryable<FeeHeadModel> FilteredItems
        {
            get
            {
                var result = feeHeadlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.FeeHeadName != null && x.FeeHeadName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.FeeHeadType != null && x.FeeHeadType.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                  (x.FeeApplicableType != null && x.FeeApplicableType.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase))
                );

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeFeeHeadStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "FeeHead/DeleteFeeHead";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}