//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class FeeMapWithClass
    {
        private ClassFeeHeadMappedModel classFeeHeadMapped = new();
        private string olddesignation = "";
        private List<ClassFeeHeadMappedModel> classFeeHeadMappedlist = new();
        private List<BranchClassModel> classlist = new();
        private List<SessionModel> sessionlist = new();
        private List<MonthModel> monthlist = new();
        private List<FeeHeadModel> feeHeadlist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        private void AddFeeMapped()
        {
            classFeeHeadMapped = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            ShowPopup = false;
            classFeeHeadMapped = new();
            StateHasChanged();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                StateHasChanged();
                var username = await sessionStorage.GetAsync<string>("UserName");
                 UserName = username.Value;
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "FeeHeadMapped/GetfeeheadMapped";
            classFeeHeadMappedlist = await httpService.Get<List<ClassFeeHeadMappedModel>>(ApiUri) ?? new();
            string ApiUri1 = "Month/GetMonth";
            classlist = await httpService.Get<List<BranchClassModel>>("BranchClass/GetClassCode") ?? new();
            monthlist = await httpService.Get<List<MonthModel>>(ApiUri1) ?? new();
            string ApiUri2 = "Session/GetSession";
            sessionlist = await httpService.Get<List<SessionModel>>(ApiUri2) ?? new();
            string ApiUri3 = "FeeHead/GetFeeHeadList";
            feeHeadlist = await httpService.Get<List<FeeHeadModel>>(ApiUri3) ?? new();
            IsLoading = false;
        }
        private async Task OnSave()
        {

            try
            {
                if (classFeeHeadMapped.ClassFeeId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(classFeeHeadMapped, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                classFeeHeadMapped.IsValid = true;
                classFeeHeadMapped.CreatedBy = UserName;
                string apiUrl = "FeeHeadMapped/AddOrUpdatefeeheadMapped";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, classFeeHeadMapped);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Class Fee Map" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Class Fee Map" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Class Fee Map" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                classFeeHeadMapped = new ();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               
                StateHasChanged();
            }
        }

        private void EditFeeMapped(ClassFeeHeadMappedModel item)
        {
            classFeeHeadMapped = new ClassFeeHeadMappedModel
            {
                ClassFeeId = item.ClassFeeId,
                FeeHeadId = item.FeeHeadId,
                ClassCode = item.ClassCode,
                SessionName = item.SessionName,
                AmountForOld = item.AmountForOld,
                Amount = item.Amount
            }; 
            olddesignation = CommonMethod.CreateSnapshot(classFeeHeadMapped);
            ShowPopup = true;
        }


        protected IQueryable<ClassFeeHeadMappedModel> FilteredItems
        {
            get
            {
                var result = classFeeHeadMappedlist.AsQueryable();
                // if (!string.IsNullOrEmpty(nameFilter))
                // {
                //     result = result.Where(x => (x.Amount != null && x.Amount.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                // (x.ClassCode != null && x.ClassCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                // }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";

        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeFeeMappedStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "FeeHeadMapped/DeletefeeheadMapped";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}