//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class PaymentMode
    {
        private PaymentModel paymentModel = new();
        private string olddesignation = "";
        private List<PaymentModel> paymentlist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string? branchcode;
        private string? groupcode;
        private string? UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }   
        private void AddPaymentModel()
        {
            paymentModel = new PaymentModel();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            ShowPopup = false;
            paymentModel = new PaymentModel();
            StateHasChanged();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                StateHasChanged();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "PaymentMode/GetBankPaymentMode";
            paymentlist = await httpService.Get<List<PaymentModel>>(ApiUri) ?? new();
            IsLoading = false;
        }

        private async Task OnSave()
        {

            try
            {
                if (paymentModel.PMId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(paymentModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                paymentModel.IsValid = true;
                paymentModel.GroupCode = groupcode;
                paymentModel.BranchCode = branchcode;
                paymentModel.CreatedBy = UserName;
                //paymentModel.CreatedDate = DateTime.Now;
                string apiUrl = "PaymentMode/AddOrUpdatePaymentMode";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, paymentModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Payment Mode" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Payment Mode" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Payment Mode" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                paymentModel = new PaymentModel();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
            }
        }

        private void EditPayment(PaymentModel item)
        {
            paymentModel = new PaymentModel
            {
                PMId = item.PMId,
                ModeName = item.ModeName,
                ModeAbbr = item.ModeAbbr,
                DisplayOrder = item.DisplayOrder
            };
            olddesignation = CommonMethod.CreateSnapshot(paymentModel);
            ShowPopup = true;
        }

        protected IQueryable<PaymentModel> FilteredItems
        {
            get
            {
                var result = paymentlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ModeName != null && x.ModeName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.ModeAbbr != null && x.ModeAbbr.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangePaymentStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "PaymentMode/DeletePaymentMode";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}