//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.FinanceMNGT;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class Society
    {
        private SocietyModel societyModel = new();
        private string olddesignation = "";
        private List<SocietyModel> societyModellist = new();
        private string nameFilter = string.Empty;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string branchcode;
        private string groupcode;
        private string UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        private void AddSociety()
        {
            societyModel = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            societyModel = new();
            ShowPopup = false;
            StateHasChanged();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData(); var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            var userResult = await sessionStorage.GetAsync<string>("UserName");
            UserName = userResult.Value;
            IsLoading = true;
            string ApiUri = "Society/ListSociety";
            societyModellist = await httpService.Get<List<SocietyModel>>(ApiUri) ?? new();
            IsLoading = false;
        }
        private async Task OnSave()
        {

            try
            {
                if (societyModel.SocietyId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(societyModel, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                societyModel.IsValid = true;
                societyModel.GroupCode = groupcode;
                societyModel.BranchCode = branchcode;
                societyModel.CreatedBy = UserName;
                string apiUrl = "Society/AddUpdateSociety";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, societyModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Society Name" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Society Name" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Society Name" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                societyModel = new SocietyModel();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
            }
        }

        private void EditSociety(SocietyModel item)
        {
            societyModel = new SocietyModel
            {
                SocietyId = item.SocietyId,
                SocietyName = item.SocietyName,
                SocietyCode = item.SocietyCode,
                SocietyDesc = item.SocietyDesc,
                BankProcessApl = item.BankProcessApl,
                BankClientCode = item.BankClientCode,
                OnlineGateway = item.OnlineGateway,
                AddressLine2 = item.AddressLine2,
                AddressLine1 = item.AddressLine1,
                hashSequence = item.hashSequence
            };
            olddesignation = CommonMethod.CreateSnapshot(societyModel);
            ShowPopup = true;
        }


        protected IQueryable<SocietyModel> FilteredItems
        {
            get
            {
                var result = societyModellist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.SocietyName != null && x.SocietyName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.SocietyCode != null && x.SocietyCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid); 
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            //StateHasChanged();
        }
        private async Task ChangeSocietyStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)

                    return;

                string apiUrl = "Society/DeleteSociety";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}