//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.FinanceMNGT;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.FinanceMNGT.FeeMNGTMasters
{
    public partial class TransportFee
    {
        private TransportFeeConfig transportFee = new();
        private string olddesignation = "";
        private List<TransportFeeConfig> transportFeelist = new();
        private string nameFilter = string.Empty;
       // private List<MstDistance> distancelist = new();
        private List<DistanceModel> distancelist = new();
        private List<SessionModel> sessionlist = new();
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private string statusFilter = "1";
        private bool IsLoading = true;
        private bool ShowPopup;
        private string? branchcode;
        private string? groupcode;
        private string? UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        private void AddTransportFee()
        {
            transportFee = new();
            ShowPopup = true;
        }
        private void ClosePopup()
        {
            transportFee = new();
            ShowPopup = false;
            StateHasChanged();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }

        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "TransportFee/GetTransport";
            //distancelist = await httpService.Get<List<MstDistance>>("ClassSection/GetDistance") ?? new();
            string ApiUri1 = "Distance/GetDistance";
            distancelist = await httpService.Get<List<DistanceModel>>(ApiUri1) ?? new();
            transportFeelist = await httpService.Get<List<TransportFeeConfig>>(ApiUri) ?? new();
            string ApiUri2 = "Session/GetSession";
            sessionlist = await httpService.Get<List<SessionModel>>(ApiUri2) ?? new();
            IsLoading = false;
        }

        private async Task OnSave()
        {

            try
            {
                if (transportFee.Tid > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(transportFee, olddesignation);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                if (transportFee.SessionId == 0)
                {
                    await Alert.ShowWarning("Please select  a session.");
                    StateHasChanged();
                    ShowPopup = true;
                    return;
                }
                transportFee.IsValid = true;
                transportFee.GroupCode = groupcode;
                transportFee.CreatedBy = UserName;
                //transportFee.CreatedDate = DateTime.Now;
                string apiUrl = "TransportFee/AddOrUpdateTransport";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, transportFee);

                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Transport Fee" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Transport Fee" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowUpdate("Transport Fee" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                transportFee = new TransportFeeConfig();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                
                StateHasChanged();
            }
        }

        private void EditTransport(TransportFeeConfig item)
        {
            transportFee = new TransportFeeConfig
            {
                Tid = item.Tid,
                DistanceId = item.DistanceId,
                SessionId=item.SessionId,
                SessionName = item.SessionName,
                Amount = item.Amount
            };
            olddesignation = CommonMethod.CreateSnapshot(transportFee);
            ShowPopup = true;
        }


        protected IQueryable<TransportFeeConfig> FilteredItems
        {
            get
            {
                var result = transportFeelist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.SessionName != null && x.SessionName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));
                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private async Task ChangeTransportStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "TransportFee/DeleteTransport";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                    StateHasChanged();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}