using System;

namespace DomainModel.Admin
{
    /// <summary>
    /// Demo/POC entity used to exercise the Controller -> Service -> Repository -> Dapper -> SP flow.
    /// Kept intentionally separate from the production Registration feature (RegistrationModal / RegistrationController)
    /// to avoid colliding with it.
    /// </summary>
    public class RegistrationDemoModel
    {
        public string GroupCode { get; set; }
        public string BranchCode { get; set; }
        public long SessionId { get; set; }

        /// <summary>Unique, auto-incremented identity generated by the database on insert.</summary>
        public int RegiNo { get; set; }

        public string StudentName { get; set; }

        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool IsValid { get; set; }
    }
}
