//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;
using System.Diagnostics.Metrics;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class ClassSubject
    {
        private bool IsLoading = true;
        private ClassSubjectModel classSubject = new();
        private string oldcdataModel = "";
        private List<ClassSubjectModel> classSubjectlist = new();
        private List<ClassCodeModel> classcodelist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string? branchcode;
        private string? groupcode;
        private string? username;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "classSubject/GetClassSubject";
            classSubjectlist = await httpService.Get<List<ClassSubjectModel>>(ApiUri) ?? new();
            string ApiUri1 = "ClassCode/GetClassCode";
            classcodelist = await httpService.Get<List<ClassCodeModel>>(ApiUri1) ?? new();
            //var result = await Http.GetFromJsonAsync<List<ClassSubjectModel>>("api/classSubject/GetclassSubject");
            //classSubjectlist = result;
            IsLoading = false;


        }
        protected IQueryable<ClassSubjectModel> FilteredItems
        {
            get
            {
                var result = classSubjectlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ClassCode != null && x.ClassCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.SubjectCode != null && x.SubjectCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddClassSubject()
        {
            classSubject = new ClassSubjectModel();
            ShowPopup = true;
        }

        private async Task OnSave()
        {

            try
            {

                if (classSubject.MapId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(classSubject, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                classSubject.IsValid = true;
                classSubject.IsCalculatedSubject = true;
                classSubject.IsOptionalSubject = true;
                classSubject.IsPracticalSubject = true;
                classSubject.IsReportCardSubject = true;
                classSubject.IsScholasticSubject = true;
                classSubject.IsCalculatedSubject = true;
                classSubject.GroupCode = groupcode;
                classSubject.BranchCode = branchcode;
                classSubject.IsLanguage = true;
                classSubject.SemesterId = 5;
                classSubject.CreatedBy = username;
                classSubject.CreatedDate = DateTime.Now;
                string apiUrl = "classSubject/AddOrUpdateClassSubject";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, classSubject);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Class subject" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Class subject" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowSuccess("Class subject" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                classSubject = new ClassSubjectModel();
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                
                StateHasChanged();
            }
        }

        private void EditClassSubject(ClassSubjectModel item)
        {
            classSubject = new ClassSubjectModel
            {
                MapId = item.MapId,
                ClassCode = item.SubjectCode,
                SubjectCode = item.SubjectCode,
                DisplayOrder = item.DisplayOrder,
            };
            oldcdataModel = CommonMethod.CreateSnapshot(classSubject);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            classSubject = new ClassSubjectModel();
            ShowPopup = false;
        }
        private async Task ChangeClassSubjectStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "classSubject/DeleteClassSubject";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}