//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentFormat.OpenXml.Wordprocessing;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.AspNetCore.Mvc;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Class
    {
        private bool IsLoading = true;
        private ClassModel classModel = new();
        private string oldcdataModel = "";
        private List<ClassModel> classlist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new();
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        HttpResponseMessage response;
        private string? groupcode;
        private string? username;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {

            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "Class/GetClass";
            classlist = await httpService.Get<List<ClassModel>>(ApiUri) ?? new();
            IsLoading = false;
        }
        protected IQueryable<ClassModel> FilteredItems
        {
            get
            {
                var result = classlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ClassName != null && x.ClassName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.ClassCode != null && x.ClassCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddClass()
        {
            classModel = new ClassModel();
            ShowPopup = true;
        }


        private async Task OnSave()
        {

            try
            {
                if (classModel.ClassId > 0)
                {

                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(classModel, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                classModel.IsValid = true;
                classModel.CreatedBy = username;
                classModel.GroupCode = groupcode;
                classModel.CreatedDate = DateTime.Now;

                string apiUrl = "Class/AddOrUpdateClass";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, classModel);
                if (classModel.ClassId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Class" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Class" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Class" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        classModel = new ClassModel();
                        await LoadData();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {

                StateHasChanged();
            }
        }

        private void EditClass(ClassModel item)
        {
            classModel = new ClassModel
            {
                ClassId = item.ClassId,
                ClassName = item.ClassName,
                ClassCode = item.ClassCode


            };
            oldcdataModel = CommonMethod.CreateSnapshot(classModel);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            classModel = new ClassModel();
            ShowPopup = false;
        }


        
        private async Task ChangeClassStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "Class/DeleteClass";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
      
    }
}