//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.AspNetCore.Mvc;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class ClassCode
    {
        private bool IsLoading = true;
        private ClassCodeModel classCodeModel = new();
        private string oldcdataModel = "";
        private List<ClassCodeModel> classcodelist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new();
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string username;
        HttpResponseMessage response;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "ClassCode/GetClassCode";
            classcodelist = await httpService.Get<List<ClassCodeModel>>(ApiUri) ?? new();
            IsLoading = false;
        }
        protected IQueryable<ClassCodeModel> FilteredItems
        {
            get
            {
                var result = classcodelist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ClassCode != null && x.ClassCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.Remarks != null && x.Remarks.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddClassCode()
        {
            classCodeModel = new();
            ShowPopup = true;
        }
        private async Task OnSave()
        {

            try
            {

                if (classCodeModel.ClassId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(classCodeModel, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                classCodeModel.IsValid = true;
                classCodeModel.CreatedBy = username;
                classCodeModel.CreatedDate = DateTime.Now;
                //classCodeModel.Remarks = "";

                string apiUrl = "ClassCode/AddOrUpdateClasscode";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, classCodeModel);
                if (classCodeModel.ClassId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Class code" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Class code" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Class code" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        await LoadData();
                        classCodeModel = new ClassCodeModel();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();
                }

            }
            catch (Exception ex)
            {
                return;
            }
            finally
            {

                StateHasChanged();
            }
        }

        private void EditClassCode(ClassCodeModel item)
        {
            classCodeModel = new ClassCodeModel
            {
                ClassId = item.ClassId,
                ClassCode = item.ClassCode,
                Remarks = item.Remarks


            };
            oldcdataModel = CommonMethod.CreateSnapshot(classCodeModel);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            classCodeModel = new ClassCodeModel();
            ShowPopup = false;
        }

       
        private async Task ChangeClassCodeStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "ClassCode/DeleteClassCode";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
        
    }
}