//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentFormat.OpenXml.Wordprocessing;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;
using ServerWebUI.Shared;
using System.Diagnostics.Metrics;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Department
    {
        private bool IsLoading = true;
        private DepartmentModel department = new();
        private string oldcdataModel = "";
        private List<DepartmentModel> departmentlist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new() { ItemsPerPage=15};
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string username;

        private string? groupcode;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {

            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "department/GetDepartment";
            departmentlist = await httpService.Get<List<DepartmentModel>>(ApiUri) ?? new();
            IsLoading = false;
        }

        protected IQueryable<DepartmentModel> FilteredItems
        {
            get
            {
                var result = departmentlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.DepartmentName != null && x.DepartmentName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.Remarks != null && x.Remarks.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddDepartment()
        {
            department = new();
            ShowPopup = true;
        }
        private async Task OnSave()
        {

            try
            {
                if (department.DepartmentId > 0)
                {

                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(department, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                department.IsValid = true;
                department.GroupCode = groupcode;
                department.DepartmentCode = "001";
                department.CreatedBy = username;
                department.CreatedDate = DateTime.Now;

                string apiUrl = "department/AddOrUpdateDepartMent";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, department);
                if (department.DepartmentId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Department" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Department" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Department" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        await LoadData();
                        department = new();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();
                   
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               
                await LoadData();
            }
        }
        private void Editdepartment(DepartmentModel item)
        {
            department = new DepartmentModel
            {
                DepartmentId = item.DepartmentId,
                DepartmentName = item.DepartmentName,
                DepartmentCode=item.DepartmentCode
            };
            oldcdataModel = CommonMethod.CreateSnapshot(department);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            department = new();
            ShowPopup = false;
            StateHasChanged();
        }

        private async Task ChangeDepartmentStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "department/DeleteDepartment";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }

    }
}