//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Gender
    {
        private EditContext editContext;
        private bool isFormValid = false;
        private bool IsLoading = true;
        private GenderModal genderModal = new();
        private string oldcdataModel = "";
        private List<GenderModal> genderModallist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new() { ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string? branchcode;
        private string? groupcode;
        private string? username;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "gender/GetGender";
            genderModallist = await httpService.Get<List<GenderModal>>(ApiUri) ?? new();

            IsLoading = false;


        }
        protected IQueryable<GenderModal> FilteredItems
        {
            get
            {
                var result = genderModallist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.GenderName != null && x.GenderName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddgenderModal()
        {
            genderModal = new GenderModal();
            ShowPopup = true;
        }

        private async Task OnSave()
        {

            try
            {

                if (genderModal.Sid > 0)
                {
                    
                ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(genderModal, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                genderModal.IsValid = true;
                genderModal.CreatedBy = username;
                genderModal.GroupCode = groupcode;
                genderModal.BranchCode = branchcode;
                genderModal.CreatedDate = DateTime.Now;
                string apiUrl = "Gender/AddOrUpdateGender";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, genderModal);
                if (apiResponse.Success)
                {
                    var responsecode = apiResponse.Code;
                    if (responsecode == 0)
                    {
                        await Alert.ShowWarning("Gender" + @Localizer["Already"]);
                    }
                    else if (responsecode == 1)
                    {
                        await Alert.ShowSuccess("Gender" + @Localizer["Inserted"]);
                    }
                    else if (responsecode == 2)
                    {
                        await Alert.ShowSuccess("Gender" + @Localizer["Updated"]);
                    }
                    else
                    {
                        await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    }
                    await LoadData();
                    genderModal = new GenderModal();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);

                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {

                StateHasChanged();
            }
        }

        private void EditGender(GenderModal item)
        {
            genderModal = new GenderModal
            {
                Sid = item.Sid,
                GenderName = item.GenderName,
                DisplayOrder = item.DisplayOrder
            };
            oldcdataModel = CommonMethod.CreateSnapshot(genderModal);
            ShowPopup = true;
        }

        private void ClosePopup()
        {

            ShowPopup = false;
            genderModal = new GenderModal();
            StateHasChanged();
        }
        private async Task ChangeGenderStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "gender/DeleteGender";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }


    }
}