//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentFormat.OpenXml.Office2010.PowerPoint;
using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Holiday
    {

        private HolidayModal holiday = new();
        private string oldcdataModel = "";
        private bool ShowPopup = false;
        private List<HolidayModal> getholidaylist = new();
        PaginationState pagination = new PaginationState { ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private bool IsLoading = true;
        private string? branchcode;
        private string? username;
        private string? groupcode; private string sessionvalue;
        private List<SessionModel> sessionlist = new();
        private string? currentUrl;
        private long CurrentSession;

        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                CurrentSession = await CommonMethod.SetCurrentSessionData();
                await LoadData();
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri = "holiday/GetHoliDay";
            getholidaylist = await httpService.Get<List<HolidayModal>>(ApiUri) ?? new();

            IsLoading = false;


        }


        protected IQueryable<HolidayModal> FilteredItems
        {
            get
            {
                var result = getholidaylist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(s => s.HolidayName.Contains(nameFilter, StringComparison.OrdinalIgnoreCase));
                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;

            }
        }

        private string GetStatusClass(bool isActive)
        {

            return isActive ? "activeClr" : "inactiveClr";

        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {
                if (holiday.HolidayId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(holiday, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                holiday.IsValid = true;
                holiday.CreatedBy = username;
                holiday.GroupCode = groupcode;
                holiday.BranchCode = branchcode;
                holiday.SessionId = CurrentSession;
                holiday.HolidayDate = DateTime.Today;
                holiday.HolidayEndDate = DateTime.Today;
                holiday.AppliedOn = "Y";
                holiday.CreatedDate = DateTime.Now;
                string apiUrl = "holiday/AddOrUpdateHoliDay";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, holiday);
                if (holiday.HolidayId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Holiday" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Holiday" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Holiday" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        await LoadData();
                        holiday = new HolidayModal();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();

                }
            }
            catch (Exception ex)
            {
                return;
            }
            finally
            {
                
                StateHasChanged();
            }

        }

        private void EditHoliday(HolidayModal item)
        {
            holiday = new HolidayModal
            {
                HolidayId = item.HolidayId,
                HolidayName = item.HolidayName,
                HolidayType = item.HolidayType,
               Remarks = item.Remarks

            };
            oldcdataModel = CommonMethod.CreateSnapshot(holiday);
            ShowPopup = true;
        }
        private async Task ChangeHolidayStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "holiday/DeleteHoliday";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    
        private void AddHoliday()
        {
            ShowPopup = true;
            holiday = new();
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            holiday = new HolidayModal();
            StateHasChanged();
        }

        private void SetCurrentSession()
        {
            var today = DateTime.Now;

            string currentSession;

            // Example: Session starts in July
            if (today.Month >= 4)
                currentSession = $"{today.Year}-{today.Year + 1}";
            else
                currentSession = $"{today.Year - 1}-{today.Year}";
            string normalize(string s) => s.Replace(" ", "").Replace("/", "-").Trim();

            var match = sessionlist
                .FirstOrDefault(x => normalize(x.SessionName) == normalize(currentSession));
            if (match != null)
            {
                sessionvalue = match.SessionName;
            }
        }
    }
}