//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.Enum;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Occupation
    {

        private OccupationModal occupation = new();
        private string oldcdataModel = "";
        private bool ShowPopup = false;
        private List<OccupationModal> getoccupationlist = new();
        PaginationState pagination = new PaginationState { ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string UserName;
        private bool IsLoading = true;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "occupation/AllOccupation";
            getoccupationlist = await httpService.Get<List<OccupationModal>>(ApiUri) ?? new();

            IsLoading = false;


        }


        protected IQueryable<OccupationModal> FilteredItems
        {
            get
            {
                var result = getoccupationlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(s => s.OccupationName.Contains(nameFilter, StringComparison.OrdinalIgnoreCase));
                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;

            }
        }

        private string GetStatusClass(bool isActive)
        {

            return isActive ? "activeClr" : "inactiveClr";

        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {

                if (occupation.OccupationId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(occupation, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                occupation.IsValid = true;
                occupation.CreatedBy = UserName;
                occupation.CreatedDate = DateTime.Now;
                string apiUrl = "occupation/AddOrUpdateOccupation";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, occupation);
                if (occupation.OccupationId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Occupation" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Occupation" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Occupation" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        await LoadData();
                        occupation = new OccupationModal();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();
                }
            }
            catch (Exception ex)
            {
                return;
            }
            finally
            {
                
                StateHasChanged();
            }

        }

        private void EditOccupation(OccupationModal item)
        {
            occupation = new OccupationModal
            {
                OccupationId = item.OccupationId,
                OccupationName = item.OccupationName,
                Type = item.Type,
                Remarks = item.Remarks

            };
            oldcdataModel = CommonMethod.CreateSnapshot(occupation);
            ShowPopup = true;
        }
        private async Task ChangeOccupationStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "occupation/DeleteOrOccupation";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }

        private void AddOccupation()
        {
            ShowPopup = true;
            occupation = new();
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            occupation = new OccupationModal();
            StateHasChanged();
        }
    }
}