//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentFormat.OpenXml.Vml.Office;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;
namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Qalification
    {
        private Qualification qualification = new();
        private string oldcdataModel = "";
        private bool ShowPopup = false;
        private List<Qualification> getqualificationlist = new();
        PaginationState pagination = new PaginationState { ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string UserName;
        private bool IsLoading = true;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "Qualification/GetQualification";
            getqualificationlist = await httpService.Get<List<Qualification>>(ApiUri) ?? new();

            IsLoading = false;


        }

        protected IQueryable<Qualification> FilteredItems
        {
            get
            {
                var result = getqualificationlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(s => s.QualificationName.Contains(nameFilter, StringComparison.OrdinalIgnoreCase));
                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid == true || s.IsValid == true);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => s.IsValid == false || s.IsValid == false);
                }
                return result;

            }
        }

        private string GetStatusClass(bool isActive)
        {

            return isActive ? "activeClr" : "inactiveClr";

        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }

        private async Task OnSave()
        {

            try
            {
                if (qualification.QualificationId > 0)
                {

                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(qualification, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                qualification.IsValid = true;
                qualification.CreatedBy = UserName;
                qualification.CreatedDate = DateTime.Now;
                var name = qualification.QualificationName?.Trim().ToLower();

                var pgList = new List<string>
                {
                    "msc","ma","mcom","mca","mtech","mba","me","mpharma","med","mfa"
                };

                if (name == "12" || name == "12th" || name == "intermediate")
                {
                    qualification.QualificationTypeId = "Intermediate";
                }
                else if (name == "10" || name == "10th" || name == "highschool" || name == "high school")
                {
                    qualification.QualificationTypeId = "HighSchool";
                }
                else if (pgList.Contains(name))
                {
                    qualification.QualificationTypeId = "PostGraduate";
                }
                else
                {
                    qualification.QualificationTypeId = "Graduate";
                }
                string apiUrl = "qualification/AddOrUpdateQualification";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, qualification);
                if (qualification.QualificationId >= 0)
                {
                    if (apiResponse.Success)
                    {
                        var responsecode = apiResponse.Code;
                        if (responsecode == 0)
                        {
                            await Alert.ShowWarning("Qualification" + @Localizer["Already"]);
                        }
                        else if (responsecode == 1)
                        {
                            await Alert.ShowSuccess("Qualification" + @Localizer["Inserted"]);
                        }
                        else if (responsecode == 2)
                        {
                            await Alert.ShowSuccess("Qualification" + @Localizer["Updated"]);
                        }
                        else
                        {
                            await Alert.ShowCustomAlert(@Localizer["Admin"]);
                        }
                        await LoadData();
                        qualification = new Qualification();
                    }
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                    await LoadData();
                }
            }
            catch (Exception ex)
            {
                return;
            }
            finally
            {
               
                StateHasChanged();
            }

        }

        private void EditQualificaion(Qualification item)
        {
            qualification = new Qualification
            {
                QualificationId = item.QualificationId,
                QualificationName = item.QualificationName,
                Remarks = item.Remarks,
                QualificationTypeId = item.QualificationTypeId

            };
            oldcdataModel = CommonMethod.CreateSnapshot(qualification);
            ShowPopup = true;
        }


        private void AddQualifiaction()
        {
            ShowPopup = true;
            qualification = new();
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            qualification = new Qualification();
            StateHasChanged();
        }
        private async Task ChangeQualificationStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "Qualification/DeleteQualification";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }


    }

}