//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ApplicationInterface.SchoolMaster;
using ApplicationInterface.SuperAdmin;
using DomainModel.Admin;
using DomainModel.Enum;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Religion
    {
        private bool IsLoading = true;
        private ReligionMaster religion = new();
        private string oldcdataModel = "";
        private List<ReligionMaster> religionlist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new()
        {
            ItemsPerPage = 15
        };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string UserName;
        HttpResponseMessage response;

        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "Religion/AllReligion";
            religionlist = await httpService.Get<List<ReligionMaster>>(ApiUri) ?? new();

            //var result = await Http.GetFromJsonAsync<List<ReligionMaster>>("api/religion/Getreligion");
            //religionlist = result;
            IsLoading = false;


        }
        protected IQueryable<ReligionMaster> FilteredItems
        {
            get
            {
                var result = religionlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.ReligionName != null && x.ReligionName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.Remarks != null && x.Remarks.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddReligion()
        {
            ShowPopup = true;
            religion = new ReligionMaster();

        }

        private async Task OnSave()
        {

            try
            {
                if (religion.ReligionId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(religion, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        ShowPopup = true;
                        return;
                    }
                }
                ShowPopup = false;
                religion.IsValid = true;
                religion.CreatedBy = UserName;
                religion.CreatedDate = DateTime.Now;
                string apiUrl = "religion/AddOrUpdateReligion";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, religion);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Religion" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Religion" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowSuccess("Religion" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                religion = new ReligionMaster();

            }
            catch (Exception)
            {
                return;
            }
            finally
            {
               
                StateHasChanged();
            }
        }

        private void EditReligion(ReligionMaster item)
        {
            religion = new ReligionMaster
            {
                ReligionId = item.ReligionId,
                ReligionName = item.ReligionName,
                Remarks = item.Remarks,
            };
            oldcdataModel = CommonMethod.CreateSnapshot(religion);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            religion = new ReligionMaster();
            StateHasChanged();
        }
        private async Task ChangeReligionStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "Religion/DeleteOrReligion";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
        //private async Task Deletereligion(int id)
        //{
        //    try
        //    {
        //        var isConfirmed = await JS.InvokeAsync<bool>("showDeleteConfirm");
        //        if (isConfirmed)
        //        {

        //            string apiUrl = "api/religion/Deletereligion";
        //            var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

        //            if (apiResponse.Success)
        //            {
        //                await Alert.ShowDeactive(@Localizer["Deleted"]);
        //                await LoadData();
        //            }
        //            else
        //            {
        //                await Alert.ShowWarning(apiResponse?.Message ?? "Something went wrong");
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        await JS.InvokeVoidAsync("Swal.fire", new
        //        {
        //            title = "Error!",
        //            text = ex.Message,
        //            icon = "error"
        //        });
        //    }
        //    finally
        //    {
        //        StateHasChanged();
        //    }
        //}

        //private async Task Activatereligion(int id)
        //{
        //    try
        //    {
        //        var isConfirmed = await JS.InvokeAsync<bool>("showActiveConfirm");
        //        if (isConfirmed)
        //        {

        //            string apiUrl = "api/religion/Deletereligion";
        //            var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

        //            if (apiResponse.Success)
        //            {
        //                await Alert.ShowActive(Localizer["Activated"]);
        //                await LoadData();
        //            }
        //            else
        //            {
        //                await Alert.ShowWarning(apiResponse?.Message ?? "Something went wrong");
        //            }

        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        await JS.InvokeVoidAsync("Swal.fire", new
        //        {
        //            title = "Error!",
        //            text = ex.Message,
        //            icon = "error"
        //        });
        //    }
        //    finally
        //    {
        //        StateHasChanged();
        //        await LoadData();

        //    }
        //}
    }
}
