//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using DocumentFormat.OpenXml.Vml.Office;
using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;
using ServerWebUI.Shared;
using System.Diagnostics.Metrics;
using System.Linq;


namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class RoleMaster
    {
        private int SelectedRoleId;
        private string SelectedRoleName = string.Empty;
        private SuperAdminDomain superAdmin;
        private string oldcdataModel = "";
        private ControlAccess controlAccess = new();
        private SuperAdminFeatures feat = new();
        private string SelectedModuleName;
        private string SelectedFeatureName="";
        private string SelectedActivityName;
        private List<SuperAdminDomain> superAdminlist = new();
        private List<DashboardModel> dashboardlist = new();
        private List<ControlAccess> controlAccessList1 = new();
        private List<SuperAdminModule> moduleList = new();
        private List<SuperAdminActivity> activitlist = new();
        private IQueryable<SuperAdminModule> moduleQuery = Enumerable.Empty<SuperAdminModule>().AsQueryable();
        private bool ShowPopup = false;
        private bool ShowPopupAdmin = false;
        private bool IsLoading = true;
        private int? SelectedModuleId;
        private int? SelectedFeatureId;
        private string SearchText = string.Empty;
        private string nameFilter = string.Empty;
        private string statusFilter = "1";
        private bool IsEditMode = false;
        private int EditingRoleId;
        private Dictionary<int, HashSet<(int ModuleId, int FeatureId)>> RoleSavedMap = new();
        public bool HasFeatures { get; set; }
        PaginationState pagination = new() { ItemsPerPage = 15 };
        private int TotalModuleCount => moduleList?.Count ?? 0;
        private string? username;
        private bool isModuleClicked = false;
        private bool isFeaturesClicked = false;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await JS.InvokeVoidAsync("menuMap");
                await LoadData();
                StateHasChanged();
              
            }
  
        }
        private void UpdateFeaturesName()
        {
            isModuleClicked = !isModuleClicked;

            if (!isModuleClicked)
            {
                SelectedModuleName = "";
                SelectedFeatureName = "";
                SelectedActivityName = "";
                return;
            }
            SelectedModuleName = "";
            SelectedFeatureName = "Features";
            SelectedActivityName = "";
        }

        private void UpdateActivityName()
        {
             isFeaturesClicked = !isFeaturesClicked;

            if (!isFeaturesClicked)
            {
                SelectedModuleName = "";
                if (SelectedFeatureName == "Features")
                {
                    SelectedActivityName = "";
                }
                SelectedFeatureName = "Features";
                
                return;
            }
            SelectedModuleName = "";
            SelectedFeatureName = "Features";
            SelectedActivityName = "Activity";
        }

        private async Task LoadData()
        {
            try
            {
                IsLoading = true;
                var userResult = await sessionStorage.GetAsync<string>("UserName");
                username = userResult.Value;
                string ApiUri = "RoleAdmin/GetAdd_Role";
                var result = await httpService.Get<ApiResponse<List<DashboardModel>>>("SuperAdminModule/GetDashboard") ?? new();
                dashboardlist = result.Data ?? new();
                superAdminlist = await httpService.Get<List<SuperAdminDomain>>(ApiUri) ?? new();
                foreach (var role in superAdminlist)
                {
                    role.IsSaved = RoleSavedMap.TryGetValue(role.RoleId, out var savedSet) && savedSet.Any();
                }
               
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            finally
            {
                IsLoading = false;
                StateHasChanged();
            }
          
            IsLoading = false;
        }
        protected IQueryable<SuperAdminDomain> FilteredItems
        {
            get
            {
                var result = superAdminlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.RoleName != null && x.RoleName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));
                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private void AddsuperAdmin()
        {
            superAdmin = new();
            ShowPopup = true;
        }
        private async Task OnSave()
        {
           
            //superAdmin.GroupCode = "01";
            //superAdmin.CreatedBy = "V3M";
            //superAdmin.CreatedDate = DateTime.Now;
            if (superAdmin.RoleId > 0)
            {
                ShowPopup = false;
                var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                if (!isConfirmed)
                {
                    ShowPopup = true;
                    return;
                }
                bool isSame = CommonMethod.IsEdited(superAdmin, oldcdataModel);
                if (!isSame)
                {
                    await Alert.ShowWarning("No changes detected.");
                    ShowPopup = true;
                    return;
                }
            }
            ShowPopup = false;
            superAdmin.IsValid = true;
            try
            {
                if (superAdmin.RoleId == 0) 
                {
                    string apiUrl = "RoleAdmin/Add_Role";
                    var apiResponse1 = await httpService.Post<ApiResponse<object>>(apiUrl, superAdmin);
                    if (!apiResponse1.Success)
                    {
                        await Alert.ShowWarning("Role" + Localizer["Already"]);
                        return;
                    }
                    await Alert.ShowSuccess("Role" + Localizer["Inserted"]);
                }
                else
                {
                    string apiUrl = "RoleAdmin/Add_RoleEdit";
                    var apiResponse1 = await httpService.Post<ApiResponse<object>>(apiUrl, superAdmin);
                    if (!apiResponse1.Success)
                    {
                        await Alert.ShowWarning(apiResponse1.Message);
                        return;
                    }
                    await Alert.ShowSuccess("Role" + @Localizer["Updated"]);

                }
                superAdmin = new();
                await LoadData();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               

                StateHasChanged();
            }
        }
        private void EditsuperAdmin(SuperAdminDomain item)
        {
            superAdmin = new SuperAdminDomain
            {
                RoleId = item.RoleId,
                RoleName = item.RoleName,
                RoleDescripation = item.RoleDescripation,
                DisplayOrder = item.DisplayOrder,
                DashBoardId=item.DashBoardId
            };
            oldcdataModel = CommonMethod.CreateSnapshot(superAdmin);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            ResetAdminState();
            ShowPopup = false;
            ShowPopupAdmin = false;
            StateHasChanged();
        }
        private async Task ChangeRoleStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "RoleAdmin/Add_RoleDelete";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);
                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();

            StateHasChanged();
        }

        private async Task OpenAdmin(SuperAdminDomain role)
        {
            try
            {
                IsLoading = true;
                string ApiUri1 = "SuperAdminModule/GetAdd_Module";
                moduleList = await httpService.Get<List<SuperAdminModule>>(ApiUri1) ?? new();
                moduleQuery = moduleList.AsQueryable();
                foreach (var module in moduleList)
                {
                    string ApiUri2 = $"SuperAdminModule/GetByModule/{module.ModuleId}";
                    module.Features = await httpService.Get<List<SuperAdminFeatures>>(ApiUri2) ?? new();
                    foreach (var feature in module.Features)
                    {
                        string ApiUri3 = $"SuperAdminModule/GetActivity/{feature.FeatureId}";
                        feature.Activites = await httpService.Get<List<SuperAdminActivity>>(ApiUri3) ?? new();
                    }
                }
                IsLoading = false;
                ResetAdminState();
                ExpandAll();
                SelectedRoleId = role.RoleId;
                SelectedRoleName = role.RoleName;

                if (RoleSavedMap.TryGetValue(role.RoleId, out var savedSet))
                {
                    foreach (var module in moduleList)
                    {
                        foreach (var feature in module.Features)
                        {
                            if (savedSet.Contains((module.ModuleId, feature.FeatureId)))
                            {
                                module.IsSaved = true;
                                feature.IsSaved = true;
                            }
                        }
                    }
                }

                await LoadRolePermissions(role.RoleId);
                ShowPopupAdmin = true;
            }
            catch (Exception)
            {

                throw;
            }
            
        }


        private void ApplySavedHighlight()
        {
            var role = superAdminlist.First(r => r.RoleId == SelectedRoleId);
            role.IsSaved = true;

            if (!RoleSavedMap.ContainsKey(SelectedRoleId))
                RoleSavedMap[SelectedRoleId] = new();

            foreach (var module in moduleList)
            {
                foreach (var feature in module.Features)
                {
                    if (feature.Activites.Any(a => a.IsSelected))
                    {
                        RoleSavedMap[SelectedRoleId]
                            .Add((module.ModuleId, feature.FeatureId));
                    }
                }
            }
        }

        private IEnumerable<SuperAdminModule> FilteredModules => string.IsNullOrWhiteSpace(SearchText) ? moduleList
        : moduleList.Where(m => !string.IsNullOrEmpty(m.MName) && m.MName.Contains(SearchText, StringComparison.OrdinalIgnoreCase));
        private void OnFeatureChecked(SuperAdminFeatures feature)
        {
            if (feature.Activites == null) return;

            foreach (var act in feature.Activites)
            {
                act.IsSelected = feature.IsSelected;
                act.IsAdd = feature.IsSelected;
                act.IsModifiy = feature.IsSelected;
                act.IsPrint = feature.IsSelected;
                act.IsExportToExcel = feature.IsSelected;
                act.IsPII = feature.IsSelected;
                act.Action1 = feature.IsSelected;
                act.Action2 = feature.IsSelected;
                act.Action3 = feature.IsSelected;
            }
        }
        //private void OnActivityChecked(SuperAdminActivity activity)
        //{
        //    if (activity. == null) return;

        //    foreach (var act in activity)
        //    {
        //        act.IsSelected = feature.IsSelected;
        //        act.IsAdd = feature.IsSelected;
        //        act.IsModifiy = feature.IsSelected;
        //        act.IsPrint = feature.IsSelected;
        //        act.IsExportToExcel = feature.IsSelected;
        //        act.IsPII = feature.IsSelected;
        //        act.Action1 = feature.IsSelected;
        //        act.Action2 = feature.IsSelected;
        //        act.Action3 = feature.IsSelected;
        //    }
        //}
        private string ToRoman(int number)
        {
            return number switch
            {
                1 => "i",
                2 => "ii",
                3 => "iii",
                4 => "iv",
                5 => "v",
                6 => "vi",
                7 => "vii",
                8 => "viii",
                9 => "ix",
                10 => "x",
                _ => number.ToString()
            };
          
        }

        private void ExpandAll()
        {
            foreach (var module in FilteredModules)
            {
                module.IsExpanded = true;

                if (module.Features != null)
                {
                    foreach (var feature in module.Features)
                    {
                        feature.IsExpanded = true;
                    }
                }
            }

        }
        private async Task LoadRolePermissions(int roleId)
        {
            var savedPermissions =
                await httpService.Get<List<ControlAccess>>($"SuperAdminModule/GetControlMappingByRole/{roleId}");

            if (savedPermissions == null || !savedPermissions.Any())
                return;

            ApplyPermissionsToUI(savedPermissions);
        }

        private void ApplyPermissionsToUI(List<ControlAccess> saved)
        {
            foreach (var module in moduleList)
            {
                foreach (var feature in module.Features)
                {
                    bool isAnyActivitySelected = false;
                    foreach (var act in feature.Activites)
                    {
                        var match = saved.FirstOrDefault(x =>
                            x.RoleId == SelectedRoleId &&
                            x.ModuleId == module.ModuleId &&
                            x.FeatureId == feature.FeatureId &&
                            x.ActivityId == act.ActivityId);

                        if (match != null)
                        {
                            isAnyActivitySelected = true;

                            act.IsSelected = true;
                            act.IsAdd = match.IsAdd;
                            act.IsModifiy = match.IsModifiy;
                            act.IsPrint = match.IsPrint;
                            act.IsExportToExcel = match.IsExportToExcel;
                            act.IsPII = match.IsPII;

                            act.Action1 = match.Action1;
                            act.Action2 = match.Action2;
                            act.Action3 = match.Action3;
                        }
                        else
                        {
                            act.IsSelected = false;
                        }
                    }
                    feature.IsSelected = isAnyActivitySelected;
                }
            }
        }

        private void ResetAdminState()
        {
            SelectedRoleId = 0;
            SelectedRoleName = string.Empty;

            SelectedModuleName = null;
            SelectedFeatureName = null;
            SelectedActivityName = null;

            superAdmin = new SuperAdminDomain();
            feat = new SuperAdminFeatures();

            foreach (var module in moduleList)
            {
                module.IsExpanded = false;

                foreach (var feature in module.Features)
                {
                    feature.IsExpanded = false;
                    feature.IsSelected = false;
                    module.IsSaved = false;
                    feature.IsSaved = false;

                    foreach (var act in feature.Activites)
                    {
                        act.IsSelected = false;
                        act.IsAdd = false;
                        act.IsModifiy = false;
                        act.IsPrint = false;
                        act.IsExportToExcel = false;
                        act.IsPII = false;
                        act.Action1 = false;
                        act.Action2 = false;
                        act.Action3 = false;
                    }
                }
            }
        }
        private async Task OnSuperAdminSave()
        {
            ShowPopupAdmin = false;

            var savedPermissions =await httpService.Get<List<ControlAccess>>( $"SuperAdminModule/GetControlMappingByRole/{SelectedRoleId}")
                ?? new List<ControlAccess>();

            var selectedActivities = moduleList .SelectMany(m => m.Features).SelectMany(f => f.Activites).Where(a => a.IsSelected).ToList();
            var controlAccessList = new List<ControlAccess>();

            foreach (var act in selectedActivities)
            {
                var feature = moduleList
                    .SelectMany(m => m.Features)
                    .First(f => f.FeatureId == act.FeatureId);

                var module = moduleList
                    .First(m => m.ModuleId == feature.ModuleId);

                controlAccessList.Add(new ControlAccess
                {
                    RoleId = SelectedRoleId,
                    ModuleId = module.ModuleId,
                    FeatureId = act.FeatureId,
                    ActivityId = act.ActivityId,
                    IsAdd = act.IsAdd,
                    IsModifiy = act.IsModifiy,
                    IsPrint = act.IsPrint,
                    IsExportToExcel = act.IsExportToExcel,
                    IsPII = act.IsPII,
                    Action1 = act.Action1,
                    Action2 = act.Action2,
                    Action3 = act.Action3,
                    CreatedBy = username
                });
            }

            var deleteList = savedPermissions.Where(sp => !selectedActivities.Any(a =>
                    a.ActivityId == sp.ActivityId &&
                    a.FeatureId == sp.FeatureId))
                .Select(sp => sp.AccessId)
                .ToList();

          
            if (controlAccessList.Any())
            {
               var apiResponse1 = await httpService.Post<ApiResponse<object>>( "SuperAdminModule/ControlMapping",controlAccessList);
                if (apiResponse1.Success)
                {
                    if (apiResponse1.ActionType == "Update")
                    {
                        await Alert.ShowSuccess("Access " + @Localizer["Updated"]);
                    }
                    else
                    {
                        await Alert.ShowSuccess("Access " + @Localizer["Saved"]);
                    }
                }
               

            }
            if (deleteList.Any())
            {
                await httpService.Post<ApiResponse<object>>( "SuperAdminModule/DeleteMapping",deleteList);
            }
            ApplySavedHighlight();
            ResetAdminState();
            StateHasChanged();

        }







       







    }
}