//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class Subject
    {
        private bool IsLoading = true;
        private SubjectModel subjectModel = new();
        private string oldcdataModel = "";
        private List<DepartmentModel> departmentlist = new();
        private List<SubjectModel> subjectlist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new(){ItemsPerPage = 15 };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string? branchcode;
        private string? groupcode;
        private string? UserName;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            var branchResult = await sessionStorage.GetAsync<string>("BranchCode");
            branchcode = branchResult.Value;
            var groupResult = await sessionStorage.GetAsync<string>("GroupCode");
            groupcode = groupResult.Value;
            IsLoading = true;
            string ApiUri1 = "department/GetDepartment";
            departmentlist = await httpService.Get<List<DepartmentModel>>(ApiUri1) ?? new();
            string ApiUri = "subject/Allsubject";
            subjectlist = await httpService.Get<List<SubjectModel>>(ApiUri) ?? new();

            //var result = await Http.GetFromJsonAsync<List<SubjectModel>>("api/subject/Getsubject");
            //subjectlist = result;
            IsLoading = false;


        }
        protected IQueryable<SubjectModel> FilteredItems
        {
            get
            {
                var result = subjectlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.SubjectName != null && x.SubjectName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.Remarks != null && x.Remarks.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddSubject()
        {
            ShowPopup = true;
            subjectModel = new SubjectModel();
 
        }

        private async Task OnSave()
        {

            try
            {
                if (subjectModel.SubjectId > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(subjectModel, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        return;
                    }

                }
                ShowPopup = false;
                subjectModel.IsValid = true;
                subjectModel.GroupCode = groupcode;
                subjectModel.BranchCode = branchcode;
                subjectModel.UGCCode = "S001";
                //subject. = "V3M";
                //subject.CreatedBy = "V3M";
                subjectModel.Credit = 10;
                subjectModel.CreatedBy = UserName;
                subjectModel.CreatedDate = DateTime.Now;
                string apiUrl = "subject/AddOrUpdatesubject";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, subjectModel);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Subject" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Subject" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowSuccess("Subject" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                subjectModel = new SubjectModel();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               
                StateHasChanged();
            }
        }

        private void EditSubject(SubjectModel item)
        {
            subjectModel = new SubjectModel
            {
                SubjectId = item.SubjectId,
                SubjectName = item.SubjectName,
                SubjectCode = item.SubjectCode,
                DepartmentId=item.DepartmentId,
                Abbreviation=item.Abbreviation,
                DisplayOrder=item.DisplayOrder,
                Remarks = item.Remarks,
            };
            oldcdataModel = CommonMethod.CreateSnapshot(subjectModel);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            subjectModel = new SubjectModel();
            StateHasChanged();
        }
        private async Task ChangeSubjectStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "subject/DeleteOrSubject";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }


}