//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DocumentFormat.OpenXml.Wordprocessing;
using DomainModel.Admin;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class SubjectCode
    {
        private bool IsLoading = true;
        private SubjectCodeMaster subjectCode = new();
        private string oldcdataModel = "";
        private List<SubjectCodeMaster> subjectCodelist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new()
        {
            ItemsPerPage = 15
        };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string UserName;
        HttpResponseMessage response;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "subjectCode/AllSubjectCode";
            subjectCodelist = await httpService.Get<List<SubjectCodeMaster>>(ApiUri) ?? new();

            //var result = await Http.GetFromJsonAsync<List<SubjectCodeMaster>>("api/subjectCode/GetsubjectCode");
            //subjectCodelist = result;
            IsLoading = false;


        }
        protected IQueryable<SubjectCodeMaster> FilteredItems
        {
            get
            {
                var result = subjectCodelist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.SubjectCode != null && x.SubjectCode.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)) ||
                (x.Remarks != null && x.Remarks.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddSubjectCode()
        {
            ShowPopup = true;
            subjectCode = new SubjectCodeMaster();

        }

        private async Task OnSave()
        {

            try
            {
                if (subjectCode.Sid > 0)
                {
                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(subjectCode, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        return;
                    }
                }

                ShowPopup = false;
                subjectCode.IsValid = true;
                subjectCode.CreatedBy = UserName;
                subjectCode.CreatedDate = DateTime.Now;
                string apiUrl = "subjectCode/AddOrUpdateSubjectCode";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, subjectCode);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("Subject code" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("Subject code" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowSuccess("Subject code" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                subjectCode = new SubjectCodeMaster();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
               
                StateHasChanged();
            }
        }

        private void EditSubjectCode(SubjectCodeMaster item)
        {
            subjectCode = new SubjectCodeMaster
            {
                Sid = item.Sid,
                SubjectCode = item.SubjectCode,
                Remarks = item.Remarks,
            };
            oldcdataModel = CommonMethod.CreateSnapshot(subjectCode);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            subjectCode = new SubjectCodeMaster();
            StateHasChanged();
        }
        private async Task ChangeSubjectCodeStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "subjectCode/DeleteOrSubjectode";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}