//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DomainModel.Admin;
using DomainModel.FinanceMNGT;
using DomainModel.SchoolMaster;
using Microsoft.AspNetCore.Components.QuickGrid;
using Microsoft.JSInterop;
using MyApp.Common;

namespace ServerWebUI.Components.Pages.SchoolMaster
{
    public partial class UserRight
    {
        private bool IsLoading = true;
        private UserRightModal userRight = new();
        private string oldcdataModel = "";
        private List<UserRightModal> userRightlist = new();
        private List<SuperAdminDomain> superAdminlist = new();
        private bool ShowPopup = false;
        PaginationState pagination = new()
        {
            ItemsPerPage = 15
        };
        string nameFilter = string.Empty;
        private string statusFilter = "1";
        private string UserName;
        HttpResponseMessage response;
        private string? currentUrl;
        protected override void OnInitialized()
        {

            PermissionState.OnChange += StateHasChanged;
            currentUrl = Nav.Uri;
            StateHasChanged();

        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                await LoadData();
                var username = await sessionStorage.GetAsync<string>("UserName");
                UserName = username.Value;
                StateHasChanged();
            }
        }
        private async Task LoadData()
        {
            IsLoading = true;
            string ApiUri = "userRight/AllUserRight";
            string ApiUri1 = "RoleAdmin/GetAdd_Role";
            superAdminlist = await httpService.Get<List<SuperAdminDomain>>(ApiUri1) ?? new();
            userRightlist = await httpService.Get<List<UserRightModal>>(ApiUri) ?? new();

            //var result = await Http.GetFromJsonAsync<List<UserRightModal>>("api/userRight/GetuserRight");
            //userRightlist = result;
            IsLoading = false;


        }
        protected IQueryable<UserRightModal> FilteredItems
        {
            get
            {
                var result = userRightlist.AsQueryable();
                if (!string.IsNullOrEmpty(nameFilter))
                {
                    result = result.Where(x => (x.UserName != null && x.UserName.Contains(nameFilter, StringComparison.CurrentCultureIgnoreCase)));

                }
                if (statusFilter == "1")
                {
                    result = result.Where(s => s.IsValid);
                }
                else if (statusFilter == "0")
                {
                    result = result.Where(s => !s.IsValid);
                }
                return result;
            }
        }
        private string GetStatusClass(bool isActive)
        {
            return isActive ? "activeClr" : "inactiveClr";
        }
        private void FilterChangedAsync(int filterValue)
        {
            statusFilter = filterValue.ToString();
            StateHasChanged();
        }
        private void AddUserRight()
        {
            ShowPopup = true;
            userRight = new UserRightModal();

        }

        private async Task OnSave()
        {

            try
            {
                if (userRight.URSID > 0)
                {

                    ShowPopup = false;
                    var isConfirmed = await JS.InvokeAsync<bool>("showUpdateConfirm");
                    if (!isConfirmed)
                    {
                        ShowPopup = true;
                        return;
                    }
                    bool isSame = CommonMethod.IsEdited(userRight, oldcdataModel);
                    if (!isSame)
                    {
                        await Alert.ShowWarning("No changes detected.");
                        return;
                    }
                }
                ShowPopup = false;
                userRight.IsValid = true;
                userRight.CreatedBy = UserName;
                userRight.CreatedDate = DateTime.Now;
                string apiUrl = "userRight/AddOrUpdateUserRight";
                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, userRight);
                var responsecode = apiResponse.Code;
                if (responsecode == 0)
                {
                    await Alert.ShowWarning("User right" + @Localizer["Already"]);
                }
                else if (responsecode == 1)
                {
                    await Alert.ShowSuccess("User right" + @Localizer["Inserted"]);
                }
                else if (responsecode == 2)
                {
                    await Alert.ShowSuccess("User right" + @Localizer["Updated"]);
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }

                await LoadData();
                userRight = new UserRightModal();

            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{@Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                
                StateHasChanged();
            }
        }

        private void EditUserRight(UserRightModal item)
        {
            userRight = new UserRightModal
            {
                URSID = item.URSID,
                UserName = item.UserName,
                RoleId = item.RoleId,
            };
            oldcdataModel = CommonMethod.CreateSnapshot(userRight);
            ShowPopup = true;
        }

        private void ClosePopup()
        {
            ShowPopup = false;
            userRight = new UserRightModal();
            StateHasChanged();
        }
        private async Task ChangeUserRightStatus(int id, bool isValid)
        {
            try
            {
                bool isActivate = !isValid;
                bool isConfirmed = await JS.InvokeAsync<bool>(isActivate ? "showActiveConfirm" : "showDeleteConfirm");
                if (!isConfirmed)
                    return;

                string apiUrl = "userRight/DeleteorUserRight";

                var apiResponse = await httpService.Post<ApiResponse<object>>(apiUrl, id);

                if (apiResponse.Success)
                {
                    if (isActivate)
                        await Alert.ShowActive(Localizer["Activated"]);
                    else
                        await Alert.ShowDeactive(Localizer["Deleted"]);

                    await LoadData();
                }
                else
                {
                    await Alert.ShowCustomAlert(@Localizer["Admin"]);
                }
            }
            catch (Exception ex)
            {
                await Alert.ShowError($"{Localizer["Error"]}: {ex.Message}");
            }
            finally
            {
                StateHasChanged();
                await LoadData();
            }
        }
    }
}